hash-format = "sha256"

[[files]]
file = "config/MiniMOTD/main.conf"
hash = "23c8e7d99167ad391841a51f23ca878c96217f3e5758364a8455aaf204ccd591"

[[files]]
file = "config/MiniMOTD/plugin_settings.conf"
hash = "06c4e746b28525d02a78c836b633ca9b16434b68d53c3fb6fc4af64132334c11"

[[files]]
file = "config/ViaFabric/viaversion.yml"
hash = "5d27461e4131c5beb3b33bd99b81866bb5f09378967a6d834fa5453705cfaa6f"

[[files]]
file = "config/badoptimizations.txt"
hash = "27cdcd366e6a4e9adc1c84d8fc969f4760e4555de06d2ccd23369bcf4134d609"

[[files]]
file = "config/entityculling.json"
hash = "7ae6e765de792c537709f8987b08ea0614c54af7df9c453c24fad79416c7420d"

[[files]]
file = "config/immediatelyfast.json"
hash = "0c8061bb4ffd018cdee1079ef31710355eb0d7e072fb2da500076a6b8d7f3a7b"

[[files]]
file = "config/lithium.properties"
hash = "9241dc5cd6caf6ddffe53a6520867c367d5cde07b5051cd198d7607de5eccb83"

[[files]]
file = "config/modmenu.json"
hash = "dc9a122de93c82269fed2fc831996b4b63f98a60aebb74ba198a2b25b22b1913"

[[files]]
file = "config/moonrise.yml"
hash = "8366e8d4fa7952e0abcf0a0871c06f0b562725b912e0d3537fc37906392a2329"

[[files]]
file = "config/moreculling.toml"
hash = "3ec60556af747b281d5f9b34b8333c3e0ea32856406532971d7126edeb2f814b"

[[files]]
file = "config/one-click-join"
hash = "84a2571389dc3fd03d7cd660d812c44500b7df165b05a92827264c66863bc404"

[[files]]
file = "config/preferred-gamerules.properties"
hash = "7efeabb366c9d0bef2054b755d8ef063d24941da5947cafd7b7b32a55fef599a"

[[files]]
file = "config/resourcepackoverrides.json"
hash = "43186c424bc7943cf321d3b487dfbb93aacbd3d8168b8ad85cb6b172f54c79d5"

[[files]]
file = "config/sodium-extra-options.json"
hash = "3b1101e8fc321f1b6587d8f0e801e09604f66afb848353f2f65b604275fb9168"

[[files]]
file = "config/sodium-options.json"
hash = "77d24fa68f21ee81998368bfb5c7afffaa206918f7da38751d6f72251335472c"

[[files]]
file = "config/voicechat/voicechat-server.properties"
hash = "1ab24276154b972b8c8db971d5f4e1be40f9101829e29fada44a83dc37568430"

[[files]]
file = "config/worldedit/schematics/Allqns - Ochame Kinou.schem"
hash = "e8a2c29ac679317044078cb9ef24aed6b51ba628b32adde8630414a76c4e07ac"

[[files]]
file = "config/worldedit/schematics/Askalotl - Dark Sanctuary.schem"
hash = "5fe7eb32cfbcf896031dbf33157fa4298e30319238fb5644804cfda19904d447"

[[files]]
file = "config/worldedit/schematics/Askalotl - THE WORLD REVOLVING.schem"
hash = "67ab85275b702e465f8eae40269bd8c721556c68d4b8646c581d4b03e620eef3"

[[files]]
file = "config/worldedit/schematics/Belodie - Beloved Tomboyish Girl.schem"
hash = "187e708f33fe6dc4fca6817104064e5c6e63feb24fc5005d5b7f6d7dced4b189"

[[files]]
file = "config/worldedit/schematics/Bentroen - Sweden - Tropical Mix.schem"
hash = "08ede607595d6bf5a573ffe58e2c2cbee531e7af48f4be9a8019827140297102"

[[files]]
file = "config/worldedit/schematics/Bizzo713 - The Outer Reaches of Space.schem"
hash = "fc7fbada629f7a23d048590e2ac7c879b8b55cd01473dc947df6e223228bb11c"

[[files]]
file = "config/worldedit/schematics/CubixL - title [SPC700].schem"
hash = "428ce36f3fb05dce9d133019b9dcc80f26f50b463ee5eb7c418c3c90c299cd0e"

[[files]]
file = "config/worldedit/schematics/Daitsuki - Aura.schem"
hash = "96ce31087ff529513e0d1ffb7bd2dfbaca5be9c1d9db83e27fa5f30af02481bb"

[[files]]
file = "config/worldedit/schematics/Dino - never gonna give you up.schem"
hash = "557dc2ff6d621ad21048b4389469265b79b5279e634303335c809454ac351fa2"

[[files]]
file = "config/worldedit/schematics/General635 - Lovesick Girls.schem"
hash = "8d8649bbbebab6f210b6ea90527c3255a4970e48c9df5b5ff2cbb29b67a55e16"

[[files]]
file = "config/worldedit/schematics/KaliumI - The Warmup.schem"
hash = "657d23df5201385e61ba49c8be39934e96b511b5b5c939a58f7261ae62b75345"

[[files]]
file = "config/worldedit/schematics/MC LEGEND 552 - AAAAAAA.ogg.schem"
hash = "00b2a7525bc548263bb1076289fb3111020569ad4745c0209779803824af927d"

[[files]]
file = "config/worldedit/schematics/Monkeylordz88 - Circus Galop.schem"
hash = "5055a377b9149a758229d45b77b337ea174ec8cd58213efebfaa0b39f5cd8be7"

[[files]]
file = "config/worldedit/schematics/NoteBlock_Covers - Linkin Park.schem"
hash = "089b627f20b66b1dd8b5d8ad7203279aff6943c9f5e179d78e38d3e9ce726b50"

[[files]]
file = "config/worldedit/schematics/OctoFlare - Alea jacta est.schem"
hash = "6a849a4cf7a07d3d8ee14c65500f8c61bab0179db760e5b585b45560f8881ba6"

[[files]]
file = "config/worldedit/schematics/Philosophy_3 - The Great Northeast My Hometown.schem"
hash = "1dcb98feab605c51234c6ab7909b1e939846a18e809aa9c5395e0c9ea70b4673"

[[files]]
file = "config/worldedit/schematics/QueasyQuery - Heat Abnormal.schem"
hash = "4ee1ac2d0ec32f9014bc6b62ae4d59757da2884d55a07fa375565897697f69a6"

[[files]]
file = "config/worldedit/schematics/Raphael Bertges - Rhapsody in Blue.schem"
hash = "2bb990000d16d76a066c22c84c9b0e92e6d038f1cae68f415a6e91ea1651f060"

[[files]]
file = "config/worldedit/schematics/Seb - Boogie.schem"
hash = "c3e9760ce560423d13be259e4ced1d828eeb56d355c026f92cfa79adf3e5f6be"

[[files]]
file = "config/worldedit/schematics/StunningWheel94 - Catswing.schem"
hash = "6f3c9b18c92d7c12296ba9da43cbe0c3c04f7948173eba7c3d3f0449b2557a0a"

[[files]]
file = "config/worldedit/schematics/Techity - SELECT.schem"
hash = "04c9bcf66c090c7c15270467ce61007df8acc4f8916f74d200cb38d0df4b655d"

[[files]]
file = "config/worldedit/schematics/Vizeon - The Drowning Citadel.schem"
hash = "61924ed7a68232b10f09371f87e25f840bb4265a6deb467cac1718bb7d43c7ca"

[[files]]
file = "config/worldedit/schematics/VoidDonpig - Adversaire Coriace.schem"
hash = "6f0c68fd710794cc19733e912f14e5499810964fc9c63aa91148d5056f2aef4e"

[[files]]
file = "config/worldedit/schematics/VoidDonpig - Ancestral Beats.schem"
hash = "8a40deaca62b9aa6a831f3988c7f334c879fbfddd6310bf1468a023716e30649"

[[files]]
file = "config/worldedit/schematics/VulkanRafar - DARLING DANCE.schem"
hash = "6bf6da927517e7082b4f1079f8558382b2267d33b8e35299d733e1278f4c2a70"

[[files]]
file = "config/worldedit/schematics/control467 - in pieces.schem"
hash = "f2efd1cc7d786290b0670af058262ce339d8642701a6866fc3a45a4e06052f73"

[[files]]
file = "config/worldedit/schematics/encode42 - The Third Sanctuary.schem"
hash = "bbfb6c54127cd7267cbd35c039bef0b3b694ebd362a8751f4ae7f9ab699f30e0"

[[files]]
file = "config/worldedit/schematics/flyingdean699 - Stay.schem"
hash = "1d35c8af81836784923ecf9df11adef86c3008b13ca59ad2fa80373fa836bbe2"

[[files]]
file = "config/worldedit/schematics/hemidemisemipresent - Flight of the Bamboo Cutter.schem"
hash = "6d341b068f24d3f46d184394b919454c6a55c537b378e37527cf61eb94de65a9"

[[files]]
file = "config/worldedit/schematics/k_lemon - NIVAW_IBKDR WlfWfI.schem"
hash = "319c649320300d0fe7f7187c44a1a065318902c0faaf7604af4d8ff20b4f5a84"

[[files]]
file = "config/worldedit/schematics/rodiroditrulala - Tau The Song.schem"
hash = "06f9442f5eb3d30741adf425e35971a5b7d76b64f74073012b3df5a3d3bce6de"

[[files]]
file = "config/worldedit/schematics/superbaconbro - SNES Mario Circuit.schem"
hash = "740f0718f56155b7cae94cb55098584bc15ae186d157f28128b63c53ec98fc7c"

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "fa80695a0289788c809bb9125c2b239370a05d6df76a08167a72b558d9daaa00"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "220695895a8fd68ca82b7b3c34d8499b4f6ea73f6588e3dfbccd2307af0b924d"
metafile = true

[[files]]
file = "mods/clientsidenoteblocks.pw.toml"
hash = "91412e14b30bbf40f9097e4cb6977464b7d0a053b1633e79acda1c3ba43ee74a"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a216e613b5ada8a83972394c8b52331388f6d3e41187a04c3bced3f1752bea70"
metafile = true

[[files]]
file = "mods/conductor-1.1.0.jar"
hash = "0d12ee13ac5a2151d9edf60bc07c4624af4fd24dcf11b5b643a4681c52d5139b"

[[files]]
file = "mods/entityculling.pw.toml"
hash = "dff937930734d00e3cd2c644d20d5015df3ad53cc9d23fae2704326774cadbad"
metafile = true

[[files]]
file = "mods/exordium.pw.toml"
hash = "c1396c86bc85ccdcb9b5e0d7e5aec00d7f4d0e73b246fb9c92672b4e7aab17ba"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "89bd18325ea4e74dd81f9c70ed2105a070d40a109bd78ae74542fa1a3935908f"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "f32210ca4e216dc112a27bb032f4da75fba87b7f4d75ce6e246a0e29c1eaea5f"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "fbf9806c22ee5bccbe08f7dec15b742f5ae3a70caf186d6dce0d42f28790f559"
metafile = true

[[files]]
file = "mods/flashback.pw.toml"
hash = "8a2b4a62ed50189fe015bb0f6907dbf016fd1f70e6f675a272f5a87f1c7c0692"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
hash = "e183674025244ef6192a3de27b8f7ba9479c2946a07d47b18c69faca939ea123"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "4cd88e9bc186b6a2136cd59690c27a8600b25f60bf2b86d429bd11a3576305ea"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "ce1a109ba7d2637596ab6b7c001716437e1bef89f337dc3fb31ca950a46e79c3"
metafile = true

[[files]]
file = "mods/ixeris.pw.toml"
hash = "9a86f61fc86604d977b2aee4a2d20fd264d635060184be5183d8e7674e4fb912"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "e26dacab5ed497b7bf6500e389eba5e21cd4b9d7b38089045cd26818a4d2f589"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "e10c94949bb58b8cfa9993a9f60c9283d5858d4d55fc450dbff2953644f45047"
metafile = true

[[files]]
file = "mods/logical-zoom.pw.toml"
hash = "29356630f876f99fa7c48a2d00e4ca4b41963719b94dbbbaa694f72ae07e5bc0"
metafile = true

[[files]]
file = "mods/luckperms.pw.toml"
hash = "5e7d7f0551f95f2f496098b0eb9f3ed4d5942ce981f4eb9e1f80c1a83ef19058"
metafile = true

[[files]]
file = "mods/luckperms/luckperms-h2-v2.mv.db"
hash = "8a5da9497b99c3570c75c9732ee5c4e4d3cf919e208f35b6eb0387962926268f"

[[files]]
file = "mods/minimotd.pw.toml"
hash = "14a079d2f5839b116e718abec0a7a8f75092b8b122fc38ccf90fff60eb834e25"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "6eea5e1db3dbca126b82f211bf0d2fcf2cf13097023fdef3dd668e48581a73d0"
metafile = true

[[files]]
file = "mods/moonrise-opt.pw.toml"
hash = "d4ed530a3a278079be0024a2c7d6309c1f577c2a0d97922fc9e7af52b9bf01a9"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "d122f53efcfd54e24ef7e15247bbebe788d4ea475c2f5b84ccc1254dc625a1ec"
metafile = true

[[files]]
file = "mods/one-click-join.pw.toml"
hash = "71edb81649aa009d008bacf7790ebe659b14cb53e41131642a1bb855b314bf35"
metafile = true

[[files]]
file = "mods/particle-core.pw.toml"
hash = "4ed5bf9e808739ddeec2692fbd7c16b3df653f1b2823de3f07e5dced1c5fc439"
metafile = true

[[files]]
file = "mods/preferred-gamerules.pw.toml"
hash = "8ba354cd42f24b7662f0eff660f5d013471b767c8e994e905b96cca8698fb3a5"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "88f9a71bf06f4959b220abab8542e4763747903e9e5ef150c38ae79c83870077"
metafile = true

[[files]]
file = "mods/simple-resource-loader.pw.toml"
hash = "072d663edf6434788b126994b7901a654efb279c4b7f503bcad4938d6d6396a5"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "1a0481b1f8bd7f92cc6095794da36f0a7de9133b48a8cccb196ac35809b4dceb"
metafile = true

[[files]]
file = "mods/skip-transitions.pw.toml"
hash = "416798b40a1c943664a194836958ad476e35b138769d649b3bf01a0becb400a8"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "b182456aefe4b8f37cc3dd34fdccbd07fcd0a2e9a6c175d5e39cd6d5190388dc"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "780646258386fccb6c92851e13dfb32b5d85cae9596ce6c829894b179245e64c"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "a6948eb25808d55a8dc3b9a64999181ebae738c3679ced2981c7c1ec34b9b0b6"
metafile = true

[[files]]
file = "mods/vanilla-permissions.pw.toml"
hash = "178eddcd5be91766f872bc7e3bdbe4f5e3774921b5f46cb704436d88c667be54"
metafile = true

[[files]]
file = "mods/viafabric.pw.toml"
hash = "d5e46e3fdaa40b3fa1ddd21baf98ec49b741be8bd0d3b3cc7b646c93ccaeb62f"
metafile = true

[[files]]
file = "mods/viaversion.pw.toml"
hash = "5e5401e6133465a593bf6eea1576a80c03a8f1a9c535ae13ae83179ced654071"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "4ae7284d8db06843377576a1bd3f61fb6b52de2a8c17bf28a6194f7f9fd538f7"
metafile = true

[[files]]
file = "ops.json"
hash = "450ed4ce12d4476fbe6c0104f285bde22c3ed018c0d5103ab64d4a61021772e1"

[[files]]
file = "options.txt"
hash = "64eaf1d8d56b5c5796813ab7e37f32e6f2a62bcf9df4434fc56f81ae4a9c1951"

[[files]]
file = "resources/datapack/required/M.A.E.S.T.R.O./pack.mcmeta"
hash = "d90d335e8c479210feb4a33210db49d7c894d5907aa3cb995eee8a6d5dc1aa65"

[[files]]
file = "resources/resourcepack/optional/Mono Note Blocks/assets/minecraft/sounds/note/banjo.ogg"
hash = "71b08db943b21a5e02aeb24afa482862053f4e240c1e4ba346d1a8b70510b2bd"

[[files]]
file = "resources/resourcepack/optional/Mono Note Blocks/assets/minecraft/sounds/note/bass.ogg"
hash = "64711a672f0cd7a5023089334ad2eaaba9c621ae5ff4a73fefcc3d7a93d6ebb3"

[[files]]
file = "resources/resourcepack/optional/Mono Note Blocks/assets/minecraft/sounds/note/bassattack.ogg"
hash = "9536cf0651c7b80b80f989f00d966b075d48edf07bf25026b83978bc78d39e32"

[[files]]
file = "resources/resourcepack/optional/Mono Note Blocks/assets/minecraft/sounds/note/bd.ogg"
hash = "2bf3d4eb3f9e48e618622cea538db42253518a80c99bd55eeed8ef64391155a5"

[[files]]
file = "resources/resourcepack/optional/Mono Note Blocks/assets/minecraft/sounds/note/bell.ogg"
hash = "b07ec37055f31a2997d052a0dba85141584129a515fe726ccc9e72788f06de2d"

[[files]]
file = "resources/resourcepack/optional/Mono Note Blocks/assets/minecraft/sounds/note/bit.ogg"
hash = "97e211a1af07a51452cd212bb190ce29f520e32817cd3620eb4a327cab34afcc"

[[files]]
file = "resources/resourcepack/optional/Mono Note Blocks/assets/minecraft/sounds/note/cow_bell.ogg"
hash = "c29127665494f43b111c946c7fa8ca119fb88bc122af4465edab84bb4a8cf4d4"

[[files]]
file = "resources/resourcepack/optional/Mono Note Blocks/assets/minecraft/sounds/note/didgeridoo.ogg"
hash = "32779723a511d33ce9c9a3cba92ba862a28a9635aa43d8ef4cdb6d70772e99d8"

[[files]]
file = "resources/resourcepack/optional/Mono Note Blocks/assets/minecraft/sounds/note/flute.ogg"
hash = "37645f2c6beb1bc6ab26fd7f18081df1fffd86472bffe5846caa5251bcdc26b9"

[[files]]
file = "resources/resourcepack/optional/Mono Note Blocks/assets/minecraft/sounds/note/guitar.ogg"
hash = "eeac1c3bc3fa85da49dab723569c56d7ec5291ee8d8305af64742e14ca608f85"

[[files]]
file = "resources/resourcepack/optional/Mono Note Blocks/assets/minecraft/sounds/note/harp.ogg"
hash = "f190831a76d6b6ac2d60aa43c403820ee01678197cc18dc9ece131c2f1527328"

[[files]]
file = "resources/resourcepack/optional/Mono Note Blocks/assets/minecraft/sounds/note/harp2.ogg"
hash = "f6e3b3eb16d46174c8a738ab7b0bea01a5d239f161cd7746b4648177c981a982"

[[files]]
file = "resources/resourcepack/optional/Mono Note Blocks/assets/minecraft/sounds/note/hat.ogg"
hash = "3a6e326f36cd7a9c04b74ec0a63ea376acb08bdb078f5393af79095038924c1a"

[[files]]
file = "resources/resourcepack/optional/Mono Note Blocks/assets/minecraft/sounds/note/icechime.ogg"
hash = "79ffcfb51a75e9a7161ca3ab73ad847db3b75c1559a16d27289f2dffd3e4aeb5"

[[files]]
file = "resources/resourcepack/optional/Mono Note Blocks/assets/minecraft/sounds/note/iron_xylophone.ogg"
hash = "6062bc8d9472dc113587e76ca86241e28a4ad8387c994e1dd80b51f1aa78828c"

[[files]]
file = "resources/resourcepack/optional/Mono Note Blocks/assets/minecraft/sounds/note/pling.ogg"
hash = "db89ab932bcc89254387b0e7b9e48782b42a87dfc42c39dbb84fda621ef1805b"

[[files]]
file = "resources/resourcepack/optional/Mono Note Blocks/assets/minecraft/sounds/note/snare.ogg"
hash = "fe367a03572bc3b816b52e6b8987583ae34a7a236c205f7b91319cab28686440"

[[files]]
file = "resources/resourcepack/optional/Mono Note Blocks/assets/minecraft/sounds/note/xylobone.ogg"
hash = "b54effd839bd846b4845ef62db9de4561f6463fe29abd4f6ad1ee1c62e6736e3"

[[files]]
file = "resources/resourcepack/optional/Mono Note Blocks/pack.mcmeta"
hash = "76b01b5f83b190448763b27b24aeec6c883285b682eb1909050d3be9f6c01613"

[[files]]
file = "resources/resourcepack/optional/Mono Note Blocks/pack.png"
hash = "5f98c835a2f7599dc6264a241112b507d06fab3bd5a896e24d8ca1973130199a"

[[files]]
file = "resources/resourcepack/required/M.A.E.S.T.R.O./assets/minecraft/textures/gui/title/background/panorama_0.png"
hash = "c51587b267883570e7e1b9c56eb3f766342ae6c662f911d41a26d2654ddfd9c1"

[[files]]
file = "resources/resourcepack/required/M.A.E.S.T.R.O./assets/minecraft/textures/gui/title/background/panorama_1.png"
hash = "8afff8f44b3cf2272b7ea5c2148ebe39e1706bdaf018e62e33cddbb9e6f3732a"

[[files]]
file = "resources/resourcepack/required/M.A.E.S.T.R.O./assets/minecraft/textures/gui/title/background/panorama_2.png"
hash = "4c1aa94f2c93637027689f36e566782343ed6df7e1db02318d4193395a9de305"

[[files]]
file = "resources/resourcepack/required/M.A.E.S.T.R.O./assets/minecraft/textures/gui/title/background/panorama_3.png"
hash = "bd5394989771df4256c33dcd467e2f30968f72832ddd9f808f3e2ab881a97ee2"

[[files]]
file = "resources/resourcepack/required/M.A.E.S.T.R.O./assets/minecraft/textures/gui/title/background/panorama_4.png"
hash = "35ea652294c8ad752eee078340921a876b4843d92937d6870d8bdeee0a2cb37d"

[[files]]
file = "resources/resourcepack/required/M.A.E.S.T.R.O./assets/minecraft/textures/gui/title/background/panorama_5.png"
hash = "69481befeeb6d8f357c3cf040a6114d8084136547c63bd861478e08c6e221b15"

[[files]]
file = "resources/resourcepack/required/M.A.E.S.T.R.O./pack.mcmeta"
hash = "16596a642d812332612f714657577d3e29a0d8a6491477a7aac1dec910492c91"

[[files]]
file = "resources/resourcepack/required/M.A.E.S.T.R.O./pack.png"
hash = "5f98c835a2f7599dc6264a241112b507d06fab3bd5a896e24d8ca1973130199a"

[[files]]
file = "resources/resourcepack/required/fusion-connected-glass.pw.toml"
hash = "cc4c03200baa367d40720320336b692e6c4fe71edbea890e27210bb2cc42408c"
metafile = true

[[files]]
file = "resources/resourcepack/required/silent-discs-plus.pw.toml"
hash = "c3f721054c06dcda3ffd986ef5933b3fbac2ac59a4bf2de894098ce7beb6fb64"
metafile = true

[[files]]
file = "saves/M.A.E.S.T.R.O./datapacks/M.A.E.S.T.R.O..zip"
hash = "160dba72011c7d31003040ff18c258455e616412936bb6d77daf8879a1b54a69"

[[files]]
file = "saves/M.A.E.S.T.R.O./entities/r.-1.-1.mca"
hash = "893da29f11ea052e1a359200b2738e5d3af9ae6eaaad173186213a504e7869e4"

[[files]]
file = "saves/M.A.E.S.T.R.O./entities/r.-1.0.mca"
hash = "cfd7900dcd8bd2ca12d853c00d69edef15e8063c3473867285aeac1506d2f0c3"

[[files]]
file = "saves/M.A.E.S.T.R.O./entities/r.0.-1.mca"
hash = "7bffb369287bcb67e8806ce95e57fabb1978539636511ac29e9301fea1145610"

[[files]]
file = "saves/M.A.E.S.T.R.O./entities/r.0.0.mca"
hash = "4c03c67b67759bd15633ba55161f5014ad949ec6c58ca93453104f80fe356bb9"

[[files]]
file = "saves/M.A.E.S.T.R.O./icon.png"
hash = "5f98c835a2f7599dc6264a241112b507d06fab3bd5a896e24d8ca1973130199a"

[[files]]
file = "saves/M.A.E.S.T.R.O./level.dat"
hash = "e088024b5a862fb2f76b651890ace7ef0ee90e0194a5203ff3074e2ef05c44e7"

[[files]]
file = "saves/M.A.E.S.T.R.O./region/r.-1.-1.mca"
hash = "654d55bff2fc69ac74b3e4ff3fe73066766c163b0ef2c259656b8971ec3729ea"

[[files]]
file = "saves/M.A.E.S.T.R.O./region/r.-1.0.mca"
hash = "987f7e0fa084b46fe3bb8bab2c8abd5c66aa1e6cb2cefab3e6462f5765930605"

[[files]]
file = "saves/M.A.E.S.T.R.O./region/r.0.-1.mca"
hash = "be03b3ce801fa785f5915d17eeb38ec4444ad7a000a8c36c830ce46c5dc9cc38"

[[files]]
file = "saves/M.A.E.S.T.R.O./region/r.0.0.mca"
hash = "74fce497b4d5f107be9837176b4605f92ecb8379431ed82fd5ee9e149ee5c593"

[[files]]
file = "server-icon.png"
hash = "7a587e8cfc286a613c37394ecee05a56964b65c04762cba5675ae2e7135085aa"

[[files]]
file = "server.properties"
hash = "79774d715f0aa5ca2bb88cf8b80cc08d15b575fba595a3dd180f169b1adc8fd6"

[[files]]
file = "servers.dat"
hash = "a51aac2deebc1e774a206896ab5d521bcee1808626ae57f7aa065e937c0e952b"
