name = "M.A.E.S.T.R.O."
author = "encode42"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca40c0d1b6f4dfe43f73b7f9d4b0938ce8da86e0e5e58ce622159e1bb0546308"

[versions]
fabric = "0.17.3"
minecraft = "1.21.8"
