name = "M.A.E.S.T.R.O."
author = "encode42"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee476fb762322c449ba5050509242962039f0b7fe8dba4c1863d093fb13d1110"

[versions]
fabric = "0.17.3"
minecraft = "1.21.8"
